version: '3.8'

networks:
  trabalhoweb:
    external: true

x-service_defaults: &service_defaults
  networks:
    - trabalhoweb
  tty: true

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: trabalhoweb
    volumes:
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "3310:3306"
    <<: *service_defaults

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/go/src
    ports:
      - "8085:8085"
    <<: *service_defaults

  frontend:
    tty: true
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8091:8091"
    <<: *service_defaults