CREATE TABLE IF NOT EXISTS Professores (
  CPF VARCHAR(11) PRIMARY KEY,
  Nome VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS Materias (
  ID VARCHAR(12) PRIMARY KEY,
  Nome VARCHAR(64) NOT NULL,
  CargaHorariaMinutos INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Aulas (
  ID VARCHAR(12) PRIMARY KEY NOT NULL,
  Data DATETIME NOT NULL,
  CargaHorariaMinutos INT NOT NULL,
  MateriaID VARCHAR(12) NOT NULL,
  Professor VARCHAR(11) NOT NULL,

  FOREIGN KEY (Professor) REFERENCES Professores(CPF),
  FOREIGN KEY (MateriaID) REFERENCES Materias(ID)
);

CREATE TABLE IF NOT EXISTS Alunos (
  GRR VARCHAR(8) PRIMARY KEY,
  Nome VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS Presencas (
  AulaID VARCHAR(12) NOT NULL,
  AlunoGRR VARCHAR(8) NOT NULL,
  Horas INT NOT NULL,

  FOREIGN KEY (AulaID) REFERENCES Aulas(ID),
  FOREIGN KEY (AlunoGRR) REFERENCES Alunos(GRR),

  PRIMARY KEY(AulaID, AlunoGRR)
);